# Root Makefile — users-module monorepo orchestrator.
#
# Delegates to sub-project Makefiles in api/, gui/, model/ via dot-namespaced
# targets (e.g. `build.api`, `test.gui`). Sub-project Makefiles follow the same
# canonical contract so they can be regenerated by @sdlcforge/gen-make.

# ---------------------------------------------------------------------------
# GNU make guard
# ---------------------------------------------------------------------------
# We require GNU make (any version — even the ancient 3.81 shipped with macOS
# is acceptable). The point is to refuse BSD make / bmake, which silently
# ignores GNU-only syntax.
ifeq ($(filter 3.% 4.%,$(MAKE_VERSION)),)
$(info ERROR: GNU make 3.81+ is required.)
$(info MAKE_VERSION is '$(MAKE_VERSION)' — this looks like BSD make / bmake or an unrecognized make.)
$(info )
$(info Install GNU make on macOS:)
$(info     brew install make)
$(info Then invoke as 'gmake' instead of 'make'.)
$(error Aborting: GNU make required)
endif

.DEFAULT_GOAL := build

SUBPROJECTS := model api gui

# ---------------------------------------------------------------------------
# Aggregate / canonical targets
# ---------------------------------------------------------------------------

.PHONY: build
build: build.model build.api build.gui ## Build all sub-projects (default)

.PHONY: test
test: test.unit ## Alias for test.unit

.PHONY: test.unit
test.unit: test.unit.model test.unit.api test.unit.gui ## Run unit tests across all sub-projects

.PHONY: test.integration
test.integration: test.integration.model test.integration.api test.integration.gui ## Run integration tests across all sub-projects

.PHONY: lint
lint: lint.model lint.api lint.gui ## Lint all sub-projects (read-only)

.PHONY: lint-fix
lint-fix: lint-fix.model lint-fix.api lint-fix.gui ## Apply lint fixes across all sub-projects

.PHONY: clean
clean: clean.model clean.api clean.gui ## Remove build artifacts (preserves generated SQL/code)

# ---------------------------------------------------------------------------
# Dev orchestration
# ---------------------------------------------------------------------------
# `dev.start` brings up the local docker-compose stack, then runs api + gui
# concurrently in the foreground. We use `make -j` style parallel invocation
# of the two run targets via a backgrounded shell + wait, which works in
# vanilla GNU make without depending on `parallel(1)`.
#
# TEMPORARY TOLERANCE: deploy/local/docker-compose.yml is delivered in
# Task 1.3. Until then, we warn and skip the compose step instead of failing
# so `make dev.start` remains usable for api+gui-only development.

DOCKER_COMPOSE_FILE := deploy/local/docker-compose.yml

.PHONY: dev.start
dev.start: ## Bring up local stack (docker-compose) and run api + gui in foreground
	@if [ -f $(DOCKER_COMPOSE_FILE) ]; then \
		echo "==> docker compose up -d ($(DOCKER_COMPOSE_FILE))"; \
		docker compose -f $(DOCKER_COMPOSE_FILE) up -d; \
	else \
		echo "WARN: $(DOCKER_COMPOSE_FILE) not found (delivered in Task 1.3) — skipping compose up."; \
	fi
	@echo "==> Starting api + gui in foreground (Ctrl-C to stop both)"
	@trap 'kill 0' INT TERM EXIT; \
		$(MAKE) -C api dev.start & \
		$(MAKE) -C gui dev.start & \
		wait

.PHONY: dev.stop
dev.stop: ## Tear down local docker-compose stack
	@if [ -f $(DOCKER_COMPOSE_FILE) ]; then \
		echo "==> docker compose down ($(DOCKER_COMPOSE_FILE))"; \
		docker compose -f $(DOCKER_COMPOSE_FILE) down; \
	else \
		echo "WARN: $(DOCKER_COMPOSE_FILE) not found (delivered in Task 1.3) — nothing to stop."; \
	fi

# ---------------------------------------------------------------------------
# Per-sub-project delegating targets (dot-namespaced)
# ---------------------------------------------------------------------------

.PHONY: build.model build.api build.gui
build.model: ; @$(MAKE) -C model build
build.api:   ; @$(MAKE) -C api   build
build.gui:   ; @$(MAKE) -C gui   build

.PHONY: test.model test.api test.gui
test.model: ; @$(MAKE) -C model test
test.api:   ; @$(MAKE) -C api   test
test.gui:   ; @$(MAKE) -C gui   test

.PHONY: test.unit.model test.unit.api test.unit.gui
test.unit.model: ; @$(MAKE) -C model test.unit
test.unit.api:   ; @$(MAKE) -C api   test.unit
test.unit.gui:   ; @$(MAKE) -C gui   test.unit

.PHONY: test.integration.model test.integration.api test.integration.gui
test.integration.model: ; @$(MAKE) -C model test.integration
test.integration.api:   ; @$(MAKE) -C api   test.integration
test.integration.gui:   ; @$(MAKE) -C gui   test.integration

.PHONY: lint.model lint.api lint.gui
lint.model: ; @$(MAKE) -C model lint
lint.api:   ; @$(MAKE) -C api   lint
lint.gui:   ; @$(MAKE) -C gui   lint

.PHONY: lint-fix.model lint-fix.api lint-fix.gui
lint-fix.model: ; @$(MAKE) -C model lint-fix
lint-fix.api:   ; @$(MAKE) -C api   lint-fix
lint-fix.gui:   ; @$(MAKE) -C gui   lint-fix

.PHONY: clean.model clean.api clean.gui
clean.model: ; @$(MAKE) -C model clean
clean.api:   ; @$(MAKE) -C api   clean
clean.gui:   ; @$(MAKE) -C gui   clean

# ---------------------------------------------------------------------------
# Help (self-documenting)
# ---------------------------------------------------------------------------
# Any target whose recipe line contains `## description` is auto-listed.

.PHONY: help
help: ## Show this help
	@echo "users-module — root Makefile"
	@echo ""
	@echo "Canonical targets:"
	@awk 'BEGIN {FS = ":.*?## "} \
		/^[a-zA-Z0-9_.\-]+:.*?## / { printf "  %-22s %s\n", $$1, $$2 }' \
		$(MAKEFILE_LIST) | sort
	@echo ""
	@echo "Per-sub-project targets follow the pattern <target>.<subproject>"
	@echo "  e.g. build.api, test.gui, lint-fix.model, clean.api"
	@echo "  sub-projects: $(SUBPROJECTS)"
