# Root Makefile — users-module monorepo orchestrator.
#
# Delegates to sub-project Makefiles in api/, gui/, model/ via dot-namespaced
# targets (e.g. `build.api`, `test.gui`). Sub-project Makefiles follow the same
# canonical contract so they can be regenerated by @sdlcforge/gen-make.

# ---------------------------------------------------------------------------
# GNU make guard
# ---------------------------------------------------------------------------
# We require GNU make (any version — even the ancient 3.81 shipped with macOS
# is acceptable). The point is to refuse BSD make / bmake, which silently
# ignores GNU-only syntax.
ifeq ($(filter 3.% 4.%,$(MAKE_VERSION)),)
$(info ERROR: GNU make 3.81+ is required.)
$(info MAKE_VERSION is '$(MAKE_VERSION)' — this looks like BSD make / bmake or an unrecognized make.)
$(info )
$(info Install GNU make on macOS:)
$(info     brew install make)
$(info Then invoke as 'gmake' instead of 'make'.)
$(error Aborting: GNU make required)
endif

.DEFAULT_GOAL := build

SUBPROJECTS := model api gui

# ---------------------------------------------------------------------------
# Preflight — verify tools + fix cross-platform deps across all sub-projects
# ---------------------------------------------------------------------------

.PHONY: preflight
preflight: preflight.model preflight.api preflight.gui ## Verify tools and fix stale deps
	@echo "  preflight complete."

.PHONY: preflight.model preflight.api preflight.gui
preflight.model: ; @$(MAKE) -C model preflight
preflight.api:   ; @$(MAKE) -C api   preflight
preflight.gui:   ; @$(MAKE) -C gui   preflight

# ---------------------------------------------------------------------------
# Aggregate / canonical targets
# ---------------------------------------------------------------------------

.PHONY: build
build: preflight build.model build.api build.gui ## Build all sub-projects (default)

.PHONY: test
test: test.unit ## Alias for test.unit

.PHONY: test.unit
test.unit: test.unit.model test.unit.api test.unit.gui ## Run unit tests across all sub-projects

.PHONY: test.integration
test.integration: test.integration.model test.integration.api test.integration.gui ## Run integration tests across all sub-projects

.PHONY: lint
lint: lint.model lint.api lint.gui ## Lint all sub-projects (read-only)

.PHONY: lint-fix
lint-fix: lint-fix.model lint-fix.api lint-fix.gui ## Apply lint fixes across all sub-projects

.PHONY: clean
clean: clean.model clean.api clean.gui ## Remove build artifacts (preserves generated SQL/code)

.PHONY: test.all
test.all: test.unit test.integration ## Run all tests (unit + integration)

# ---------------------------------------------------------------------------
# Dev orchestration
# ---------------------------------------------------------------------------
# `dev.start` runs the full stack in Docker containers:
#   - Postgres, Authelia, Mailpit (infrastructure)
#   - API server (Go, built from source, runs migrations on start)
#   - GUI dev server (Next.js with hot-reload via volume mounts)
#
# All services publish ports to localhost for browser access.
# Ctrl-C stops all containers.

DOCKER_COMPOSE_FILE := deploy/local/docker-compose.yml

# Auto-detect docker compose command (v2 plugin or v1 standalone).
DOCKER_COMPOSE := $(shell \
	if docker compose version >/dev/null 2>&1; then echo "docker compose"; \
	elif command -v docker-compose >/dev/null 2>&1; then echo "docker-compose"; \
	else echo ""; fi)

.PHONY: dev.start
dev.start: _dev.preflight _dev.env _dev.urls ## Build and run full stack in Docker
	@$(DOCKER_COMPOSE) -f $(DOCKER_COMPOSE_FILE) up --build --remove-orphans

.PHONY: _dev.preflight
_dev.preflight:
ifeq ($(DOCKER_COMPOSE),)
	$(error docker compose (v2 plugin) or docker-compose (v1) is required but neither was found)
endif
	@command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is required."; exit 1; }
	@if ! grep -E '^[[:space:]]*127\.' /etc/hosts 2>/dev/null | grep -qw authelia; then \
		echo ""; \
		echo "  WARNING: /etc/hosts does not have an 'authelia' entry pointing at 127.0.0.1."; \
		echo "  The 'Sign in with Authelia' button in the GUI will fail to reach Authelia"; \
		echo "  from your browser. Add this line to /etc/hosts:"; \
		echo "      127.0.0.1  authelia"; \
		echo "  See deploy/local/README.md for details."; \
		echo ""; \
	fi

.PHONY: _dev.env
_dev.env:
	@if [ ! -f .env ]; then \
		echo "==> .env not found — copying from .env.example"; \
		cp .env.example .env; \
	fi
	@if [ ! -f deploy/local/authelia/certs/cert.pem ]; then \
		echo "==> Generating self-signed TLS cert for Authelia..."; \
		mkdir -p deploy/local/authelia/certs; \
		openssl req -x509 -nodes -newkey rsa:2048 \
			-keyout deploy/local/authelia/certs/key.pem \
			-out deploy/local/authelia/certs/cert.pem \
			-days 3650 -subj "/CN=127.0.0.1" \
			-addext "subjectAltName=IP:127.0.0.1,DNS:localhost,DNS:authelia" 2>/dev/null; \
	fi

.PHONY: _dev.urls
_dev.urls:
	@echo ""
	@echo "========================================================================"
	@echo "  users-module local dev stack"
	@echo ""
	@echo "  GUI (login here):   http://localhost:3000/auth/login"
	@echo "  API:                http://localhost:8080"
	@echo "  API health:         http://localhost:8080/healthz"
	@echo "  Mailpit (emails):   http://localhost:8025"
	@echo "  Authelia (OIDC):    http://localhost:9091"
	@echo "  Postgres:           localhost:5432  (users/users)"
	@echo ""
	@echo "  First registered user automatically gets admin privileges."
	@echo "  Ctrl-C to stop all containers."
	@echo "========================================================================"
	@echo ""

.PHONY: dev.stop
dev.stop: ## Tear down all dev containers
ifeq ($(DOCKER_COMPOSE),)
	$(error docker compose (v2 plugin) or docker-compose (v1) is required but neither was found)
endif
	@$(DOCKER_COMPOSE) -f $(DOCKER_COMPOSE_FILE) down --remove-orphans
	@docker rm -f users-module-postgres users-module-authelia users-module-mailpit users-module-mailhog users-module-api users-module-gui 2>/dev/null || true

# ---------------------------------------------------------------------------
# Per-sub-project delegating targets (dot-namespaced)
# ---------------------------------------------------------------------------

.PHONY: build.model build.api build.gui
build.model: ; @$(MAKE) -C model build
build.api:   ; @$(MAKE) -C api   build
build.gui:   ; @$(MAKE) -C gui   build

.PHONY: test.model test.api test.gui
test.model: ; @$(MAKE) -C model test
test.api:   ; @$(MAKE) -C api   test
test.gui:   ; @$(MAKE) -C gui   test

.PHONY: test.unit.model test.unit.api test.unit.gui
test.unit.model: ; @$(MAKE) -C model test.unit
test.unit.api:   ; @$(MAKE) -C api   test.unit
test.unit.gui:   ; @$(MAKE) -C gui   test.unit

.PHONY: test.integration.model test.integration.api test.integration.gui
test.integration.model: ; @$(MAKE) -C model test.integration
test.integration.api:   ; @$(MAKE) -C api   test.integration
test.integration.gui:   ; @$(MAKE) -C gui   test.integration

.PHONY: lint.model lint.api lint.gui
lint.model: ; @$(MAKE) -C model lint
lint.api:   ; @$(MAKE) -C api   lint
lint.gui:   ; @$(MAKE) -C gui   lint

.PHONY: lint-fix.model lint-fix.api lint-fix.gui
lint-fix.model: ; @$(MAKE) -C model lint-fix
lint-fix.api:   ; @$(MAKE) -C api   lint-fix
lint-fix.gui:   ; @$(MAKE) -C gui   lint-fix

.PHONY: clean.model clean.api clean.gui
clean.model: ; @$(MAKE) -C model clean
clean.api:   ; @$(MAKE) -C api   clean
clean.gui:   ; @$(MAKE) -C gui   clean

# ---------------------------------------------------------------------------
# Container image
# ---------------------------------------------------------------------------

.PHONY: image.build
image.build: ## Build OCI container image locally via ko
	@command -v ko >/dev/null 2>&1 || { echo "ERROR: ko not found. Install: go install github.com/google/ko@latest"; exit 1; }
	KO_DOCKER_REPO=ko.local ko build --local ./api/cmd/server

# ---------------------------------------------------------------------------
# OpenAPI
# ---------------------------------------------------------------------------

.PHONY: openapi.validate
openapi.validate: ## Validate the OpenAPI spec (requires spectral or python3+pyyaml)
	@if command -v spectral >/dev/null 2>&1; then \
		spectral lint api/openapi.yaml; \
	elif command -v python3 >/dev/null 2>&1; then \
		python3 -c "import yaml, sys; yaml.safe_load(open('api/openapi.yaml')); print('api/openapi.yaml: YAML syntax OK')"; \
	else \
		echo "WARN: neither spectral nor python3 found — skipping validation"; \
	fi

# ---------------------------------------------------------------------------
# Model-specific delegating targets
# ---------------------------------------------------------------------------

.PHONY: model.migrate.new
model.migrate.new: ## Create a new migration (NAME=… required)
	@$(MAKE) -C model migrate.new NAME=$(NAME)

.PHONY: model.migrate.up
model.migrate.up: ## Apply pending model migrations
	@$(MAKE) -C model migrate.up

.PHONY: model.migrate.status
model.migrate.status: ## Show model migration status
	@$(MAKE) -C model migrate.status

.PHONY: model.migrate.hash
model.migrate.hash: ## Recalculate model migration hash
	@$(MAKE) -C model migrate.hash

.PHONY: model.gen
model.gen: ## Generate Go code from model queries
	@$(MAKE) -C model gen

.PHONY: model.verify
model.verify: ## Validate model migrations + queries
	@$(MAKE) -C model verify

# ---------------------------------------------------------------------------
# Help (self-documenting)
# ---------------------------------------------------------------------------
# Any target whose recipe line contains `## description` is auto-listed.

.PHONY: help
help: ## Show this help
	@echo "users-module — root Makefile"
	@echo ""
	@echo "Canonical targets:"
	@awk 'BEGIN {FS = ":.*?## "} \
		/^[a-zA-Z0-9_.\-]+:.*?## / { printf "  %-22s %s\n", $$1, $$2 }' \
		$(MAKEFILE_LIST) | sort
	@echo ""
	@echo "Per-sub-project targets follow the pattern <target>.<subproject>"
	@echo "  e.g. build.api, test.gui, lint-fix.model, clean.api"
	@echo "  sub-projects: $(SUBPROJECTS)"
