// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: apps_user_accounts.sql

package db

import (
	"context"
)

const assignUserAccountToApp = `-- name: AssignUserAccountToApp :exec
INSERT INTO apps_user_accounts (app_id, user_account_id, roles)
VALUES ($1, $2, $3)
ON CONFLICT (app_id, user_account_id) DO NOTHING
`

type AssignUserAccountToAppParams struct {
	AppID         int64    `json:"app_id"`
	UserAccountID int64    `json:"user_account_id"`
	Roles         []string `json:"roles"`
}

func (q *Queries) AssignUserAccountToApp(ctx context.Context, arg AssignUserAccountToAppParams) error {
	_, err := q.db.Exec(ctx, assignUserAccountToApp, arg.AppID, arg.UserAccountID, arg.Roles)
	return err
}

const listAppUserAccounts = `-- name: ListAppUserAccounts :many
SELECT app_id, user_account_id, roles, assigned_at
FROM apps_user_accounts
WHERE app_id = $1
ORDER BY assigned_at
`

func (q *Queries) ListAppUserAccounts(ctx context.Context, appID int64) ([]AppsUserAccount, error) {
	rows, err := q.db.Query(ctx, listAppUserAccounts, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppsUserAccount
	for rows.Next() {
		var i AppsUserAccount
		if err := rows.Scan(
			&i.AppID,
			&i.UserAccountID,
			&i.Roles,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccountApps = `-- name: ListUserAccountApps :many
SELECT app_id, user_account_id, roles, assigned_at
FROM apps_user_accounts
WHERE user_account_id = $1
ORDER BY assigned_at
`

func (q *Queries) ListUserAccountApps(ctx context.Context, userAccountID int64) ([]AppsUserAccount, error) {
	rows, err := q.db.Query(ctx, listUserAccountApps, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppsUserAccount
	for rows.Next() {
		var i AppsUserAccount
		if err := rows.Scan(
			&i.AppID,
			&i.UserAccountID,
			&i.Roles,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserAccountFromApp = `-- name: RemoveUserAccountFromApp :exec
DELETE FROM apps_user_accounts
WHERE app_id = $1 AND user_account_id = $2
`

type RemoveUserAccountFromAppParams struct {
	AppID         int64 `json:"app_id"`
	UserAccountID int64 `json:"user_account_id"`
}

func (q *Queries) RemoveUserAccountFromApp(ctx context.Context, arg RemoveUserAccountFromAppParams) error {
	_, err := q.db.Exec(ctx, removeUserAccountFromApp, arg.AppID, arg.UserAccountID)
	return err
}

const setAppUserAccountRoles = `-- name: SetAppUserAccountRoles :exec
UPDATE apps_user_accounts
SET roles = $3
WHERE app_id = $1 AND user_account_id = $2
`

type SetAppUserAccountRolesParams struct {
	AppID         int64    `json:"app_id"`
	UserAccountID int64    `json:"user_account_id"`
	Roles         []string `json:"roles"`
}

func (q *Queries) SetAppUserAccountRoles(ctx context.Context, arg SetAppUserAccountRolesParams) error {
	_, err := q.db.Exec(ctx, setAppUserAccountRoles, arg.AppID, arg.UserAccountID, arg.Roles)
	return err
}
