// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditByActor = `-- name: ListAuditByActor :many
SELECT id, actor_user_account_id, assumed_user_account_id, target_entity_id, op, resource, before, after, at
FROM audit_log
WHERE actor_user_account_id = $1
ORDER BY at DESC
LIMIT $2 OFFSET $3
`

type ListAuditByActorParams struct {
	ActorUserAccountID int64 `json:"actor_user_account_id"`
	Limit              int32 `json:"limit"`
	Offset             int32 `json:"offset"`
}

func (q *Queries) ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByActor, arg.ActorUserAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserAccountID,
			&i.AssumedUserAccountID,
			&i.TargetEntityID,
			&i.Op,
			&i.Resource,
			&i.Before,
			&i.After,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTarget = `-- name: ListAuditByTarget :many
SELECT id, actor_user_account_id, assumed_user_account_id, target_entity_id, op, resource, before, after, at
FROM audit_log
WHERE target_entity_id = $1
ORDER BY at DESC
LIMIT $2 OFFSET $3
`

type ListAuditByTargetParams struct {
	TargetEntityID pgtype.Int8 `json:"target_entity_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTarget, arg.TargetEntityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserAccountID,
			&i.AssumedUserAccountID,
			&i.TargetEntityID,
			&i.Op,
			&i.Resource,
			&i.Before,
			&i.After,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAudit = `-- name: ListRecentAudit :many
SELECT id, actor_user_account_id, assumed_user_account_id, target_entity_id, op, resource, before, after, at
FROM audit_log
ORDER BY at DESC
LIMIT $1 OFFSET $2
`

type ListRecentAuditParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserAccountID,
			&i.AssumedUserAccountID,
			&i.TargetEntityID,
			&i.Op,
			&i.Resource,
			&i.Before,
			&i.After,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAudit = `-- name: WriteAudit :exec
INSERT INTO audit_log (actor_user_account_id, assumed_user_account_id, target_entity_id, op, resource, before, after)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type WriteAuditParams struct {
	ActorUserAccountID   int64       `json:"actor_user_account_id"`
	AssumedUserAccountID pgtype.Int8 `json:"assumed_user_account_id"`
	TargetEntityID       pgtype.Int8 `json:"target_entity_id"`
	Op                   string      `json:"op"`
	Resource             string      `json:"resource"`
	Before               []byte      `json:"before"`
	After                []byte      `json:"after"`
}

func (q *Queries) WriteAudit(ctx context.Context, arg WriteAuditParams) error {
	_, err := q.db.Exec(ctx, writeAudit,
		arg.ActorUserAccountID,
		arg.AssumedUserAccountID,
		arg.TargetEntityID,
		arg.Op,
		arg.Resource,
		arg.Before,
		arg.After,
	)
	return err
}
