// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: email_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailCode = `-- name: ConsumeEmailCode :exec
UPDATE email_codes
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeEmailCode, id)
	return err
}

const createEmailCode = `-- name: CreateEmailCode :one
INSERT INTO email_codes (user_account_id, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_account_id, code_hash, purpose, expires_at, consumed_at, created_at
`

type CreateEmailCodeParams struct {
	UserAccountID int64              `json:"user_account_id"`
	CodeHash      string             `json:"code_hash"`
	Purpose       string             `json:"purpose"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, createEmailCode,
		arg.UserAccountID,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.CodeHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEmailCode = `-- name: GetActiveEmailCode :one
SELECT id, user_account_id, code_hash, purpose, expires_at, consumed_at, created_at
FROM email_codes
WHERE user_account_id = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveEmailCodeParams struct {
	UserAccountID int64  `json:"user_account_id"`
	Purpose       string `json:"purpose"`
}

func (q *Queries) GetActiveEmailCode(ctx context.Context, arg GetActiveEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, getActiveEmailCode, arg.UserAccountID, arg.Purpose)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.CodeHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
