// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

type AppsUserAccount struct {
	AppID         int64              `json:"app_id"`
	UserAccountID int64              `json:"user_account_id"`
	Roles         []string           `json:"roles"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
}

type AuthLocal struct {
	UserAccountID     int64              `json:"user_account_id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type EmailCode struct {
	ID            int64              `json:"id"`
	UserAccountID int64              `json:"user_account_id"`
	CodeHash      string             `json:"code_hash"`
	Purpose       string             `json:"purpose"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    *time.Time         `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OidcConfig struct {
	ID                  int32              `json:"id"`
	OptOut              bool               `json:"opt_out"`
	SetupTokenHash      pgtype.Text        `json:"setup_token_hash"`
	SetupTokenCreatedAt *time.Time         `json:"setup_token_created_at"`
	SavedAt             pgtype.Timestamptz `json:"saved_at"`
}

type OidcProvider struct {
	ID           string             `json:"id"`
	DisplayName  pgtype.Text        `json:"display_name"`
	IssuerUrl    pgtype.Text        `json:"issuer_url"`
	ClientID     pgtype.Text        `json:"client_id"`
	ClientSecret pgtype.Text        `json:"client_secret"`
	ClaimStyle   pgtype.Text        `json:"claim_style"`
	Scopes       []string           `json:"scopes"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	ID            int64              `json:"id"`
	UserAccountID int64              `json:"user_account_id"`
	TokenHash     string             `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    *time.Time         `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UserAccount struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	AccountHolder   int64              `json:"account_holder"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	IsAdmin         bool               `json:"is_admin"`
	DefaultAppID    pgtype.Int8        `json:"default_app_id"`
	AuthIssuer      pgtype.Text        `json:"auth_issuer"`
	AuthID          pgtype.Text        `json:"auth_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
