// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oidc_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :execrows
DELETE FROM oidc_providers WHERE id = $1
`

// Remove a provider override row. Used by the "revert" endpoint — after
// deletion the merge layer falls back to env + well-known defaults.
// Returns the number of rows deleted so the handler can distinguish
// 204 (deleted) from 404 (never existed).
func (q *Queries) DeleteOIDCProvider(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOIDCProvider = `-- name: GetOIDCProvider :one
SELECT id, display_name, issuer_url, client_id, client_secret,
       claim_style, scopes, enabled, created_at, updated_at
FROM oidc_providers
WHERE id = $1
`

// Fetch one provider override row by id.
func (q *Queries) GetOIDCProvider(ctx context.Context, id string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProvider, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.ClaimStyle,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, display_name, issuer_url, client_id, client_secret,
       claim_style, scopes, enabled, created_at, updated_at
FROM oidc_providers
ORDER BY id
`

// Return every provider override row, sorted by id for stable output.
func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcProvider
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.ClaimStyle,
			&i.Scopes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOIDCProviderEnabled = `-- name: SetOIDCProviderEnabled :exec
INSERT INTO oidc_providers (id, enabled)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetOIDCProviderEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

// Narrow write used by /v1/oidc-config/confirm when the admin toggles a
// provider on/off from the summary page. Insert creates a row with just
// the enabled flag (all other override fields NULL → pass through to env
// / well-known); update leaves all other columns untouched so the row's
// existing overrides survive a simple enable/disable.
func (q *Queries) SetOIDCProviderEnabled(ctx context.Context, arg SetOIDCProviderEnabledParams) error {
	_, err := q.db.Exec(ctx, setOIDCProviderEnabled, arg.ID, arg.Enabled)
	return err
}

const upsertOIDCProvider = `-- name: UpsertOIDCProvider :one
INSERT INTO oidc_providers (
    id, display_name, issuer_url, client_id, client_secret,
    claim_style, scopes, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    display_name  = EXCLUDED.display_name,
    issuer_url    = EXCLUDED.issuer_url,
    client_id     = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    claim_style   = EXCLUDED.claim_style,
    scopes        = EXCLUDED.scopes,
    enabled       = EXCLUDED.enabled
RETURNING id, display_name, issuer_url, client_id, client_secret,
          claim_style, scopes, enabled, created_at, updated_at
`

type UpsertOIDCProviderParams struct {
	ID           string      `json:"id"`
	DisplayName  pgtype.Text `json:"display_name"`
	IssuerUrl    pgtype.Text `json:"issuer_url"`
	ClientID     pgtype.Text `json:"client_id"`
	ClientSecret pgtype.Text `json:"client_secret"`
	ClaimStyle   pgtype.Text `json:"claim_style"`
	Scopes       []string    `json:"scopes"`
	Enabled      bool        `json:"enabled"`
}

// Insert or replace a provider override row. NULL override fields mean
// "no opinion at this layer"; the merge code treats NULL as pass-through
// to env / well-known defaults.
//
// The handler is responsible for computing the merged row before
// calling: partial PATCH semantics (e.g. "keep existing client_secret
// when field is omitted") must be resolved in Go code, because SQL
// NULL doesn't distinguish "field absent" from "explicit null". This
// keeps the query trivial and the semantics readable.
func (q *Queries) UpsertOIDCProvider(ctx context.Context, arg UpsertOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, upsertOIDCProvider,
		arg.ID,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.ClaimStyle,
		arg.Scopes,
		arg.Enabled,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.ClaimStyle,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
