// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oidc_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSetupTokenHash = `-- name: ClearSetupTokenHash :exec
UPDATE oidc_config
SET setup_token_hash = NULL,
    setup_token_created_at = NULL
WHERE id = 1
`

// Clear the setup token once the operator has confirmed configuration.
// Idempotent — safe to call on every confirmed boot.
func (q *Queries) ClearSetupTokenHash(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearSetupTokenHash)
	return err
}

const getOIDCConfig = `-- name: GetOIDCConfig :one
SELECT id, opt_out, setup_token_hash, setup_token_created_at, saved_at
FROM oidc_config
WHERE id = 1
`

func (q *Queries) GetOIDCConfig(ctx context.Context) (OidcConfig, error) {
	row := q.db.QueryRow(ctx, getOIDCConfig)
	var i OidcConfig
	err := row.Scan(
		&i.ID,
		&i.OptOut,
		&i.SetupTokenHash,
		&i.SetupTokenCreatedAt,
		&i.SavedAt,
	)
	return i, err
}

const setSetupTokenHash = `-- name: SetSetupTokenHash :exec
UPDATE oidc_config
SET setup_token_hash = $1,
    setup_token_created_at = now()
WHERE id = 1
`

// Install or refresh the active setup-token hash; called once per boot
// when the state is unconfirmed and no hash is already present.
func (q *Queries) SetSetupTokenHash(ctx context.Context, setupTokenHash pgtype.Text) error {
	_, err := q.db.Exec(ctx, setSetupTokenHash, setupTokenHash)
	return err
}

const updateOIDCConfig = `-- name: UpdateOIDCConfig :exec
UPDATE oidc_config
SET opt_out = $1,
    saved_at = now()
WHERE id = 1
`

// Persist the operator's opt-out choice (called from POST /v1/oidc-config/confirm).
// Per-provider enable flags live in the oidc_providers table and are
// upserted directly — no JSONB column on this singleton since 9.16.
func (q *Queries) UpdateOIDCConfig(ctx context.Context, optOut bool) error {
	_, err := q.db.Exec(ctx, updateOIDCConfig, optOut)
	return err
}
