// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveApp(ctx context.Context, id int64) error
	AssignUserAccountToApp(ctx context.Context, arg AssignUserAccountToAppParams) error
	// Clear the setup token once the operator has confirmed configuration.
	// Idempotent — safe to call on every confirmed boot.
	ClearSetupTokenHash(ctx context.Context) error
	ConsumeEmailCode(ctx context.Context, id int64) error
	ConsumePasswordReset(ctx context.Context, id int64) error
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeleteAuthLocal(ctx context.Context, userAccountID int64) error
	// Remove a provider override row. Used by the "revert" endpoint — after
	// deletion the merge layer falls back to env + well-known defaults.
	// Returns the number of rows deleted so the handler can distinguish
	// 204 (deleted) from 404 (never existed).
	DeleteOIDCProvider(ctx context.Context, id string) (int64, error)
	GetActiveEmailCode(ctx context.Context, arg GetActiveEmailCodeParams) (EmailCode, error)
	GetActivePasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetAppBySlug(ctx context.Context, slug string) (App, error)
	GetAppByUUID(ctx context.Context, argUuid uuid.UUID) (App, error)
	GetAuthLocal(ctx context.Context, userAccountID int64) (AuthLocal, error)
	GetOIDCConfig(ctx context.Context) (OidcConfig, error)
	// Fetch one provider override row by id.
	GetOIDCProvider(ctx context.Context, id string) (OidcProvider, error)
	GetUserAccountByAuth(ctx context.Context, arg GetUserAccountByAuthParams) (UserAccount, error)
	GetUserAccountByEmail(ctx context.Context, lower string) (UserAccount, error)
	GetUserAccountByID(ctx context.Context, id int64) (UserAccount, error)
	GetUserAccountByUUID(ctx context.Context, argUuid uuid.UUID) (UserAccount, error)
	ListAppUserAccounts(ctx context.Context, appID int64) ([]AppsUserAccount, error)
	ListApps(ctx context.Context) ([]App, error)
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	// Return every provider override row, sorted by id for stable output.
	ListOIDCProviders(ctx context.Context) ([]OidcProvider, error)
	ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error)
	ListUserAccountApps(ctx context.Context, userAccountID int64) ([]AppsUserAccount, error)
	RemoveUserAccountFromApp(ctx context.Context, arg RemoveUserAccountFromAppParams) error
	SearchUserAccounts(ctx context.Context, arg SearchUserAccountsParams) ([]UserAccount, error)
	SetAdmin(ctx context.Context, arg SetAdminParams) error
	SetAppUserAccountRoles(ctx context.Context, arg SetAppUserAccountRolesParams) error
	SetDefaultApp(ctx context.Context, arg SetDefaultAppParams) error
	// Narrow write used by /v1/oidc-config/confirm when the admin toggles a
	// provider on/off from the summary page. Insert creates a row with just
	// the enabled flag (all other override fields NULL → pass through to env
	// / well-known); update leaves all other columns untouched so the row's
	// existing overrides survive a simple enable/disable.
	SetOIDCProviderEnabled(ctx context.Context, arg SetOIDCProviderEnabledParams) error
	// Install or refresh the active setup-token hash; called once per boot
	// when the state is unconfirmed and no hash is already present.
	SetSetupTokenHash(ctx context.Context, setupTokenHash pgtype.Text) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
	// Persist the operator's opt-out choice (called from POST /v1/oidc-config/confirm).
	// Per-provider enable flags live in the oidc_providers table and are
	// upserted directly — no JSONB column on this singleton since 9.16.
	UpdateOIDCConfig(ctx context.Context, optOut bool) error
	UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) error
	UpsertAuthLocal(ctx context.Context, arg UpsertAuthLocalParams) error
	// Insert or replace a provider override row. NULL override fields mean
	// "no opinion at this layer"; the merge code treats NULL as pass-through
	// to env / well-known defaults.
	//
	// The handler is responsible for computing the merged row before
	// calling: partial PATCH semantics (e.g. "keep existing client_secret
	// when field is omitted") must be resolved in Go code, because SQL
	// NULL doesn't distinguish "field absent" from "explicit null". This
	// keeps the query trivial and the semantics readable.
	UpsertOIDCProvider(ctx context.Context, arg UpsertOIDCProviderParams) (OidcProvider, error)
	WriteAudit(ctx context.Context, arg WriteAuditParams) error
}

var _ Querier = (*Queries)(nil)
