// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveApp(ctx context.Context, id int64) error
	ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	AssignUserToApp(ctx context.Context, arg AssignUserToAppParams) error
	// Clear the setup token once the operator has confirmed configuration.
	// Idempotent — safe to call on every confirmed boot.
	ClearSetupTokenHash(ctx context.Context) error
	ConsumeEmailCode(ctx context.Context, id int64) error
	ConsumePasswordReset(ctx context.Context, id int64) error
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error)
	CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error)
	CreateEntity(ctx context.Context, kind string) (Entity, error)
	CreateLegalEntity(ctx context.Context, arg CreateLegalEntityParams) (LegalEntity, error)
	CreateNaturalPerson(ctx context.Context, arg CreateNaturalPersonParams) (NaturalPerson, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthLocal(ctx context.Context, userID int64) error
	// Remove a provider override row. Used by the "revert" endpoint — after
	// deletion the merge layer falls back to env + well-known defaults.
	// Returns the number of rows deleted so the handler can distinguish
	// 204 (deleted) from 404 (never existed).
	DeleteOIDCProvider(ctx context.Context, id string) (int64, error)
	GetActiveEmailCode(ctx context.Context, arg GetActiveEmailCodeParams) (EmailCode, error)
	GetActivePasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetAppBySlug(ctx context.Context, slug string) (App, error)
	GetAppByUUID(ctx context.Context, argUuid uuid.UUID) (App, error)
	GetAuthLocal(ctx context.Context, userID int64) (AuthLocal, error)
	GetCorporationByLegalEntityID(ctx context.Context, legalEntityID int64) (Corporation, error)
	GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (Entity, error)
	GetLegalEntityByEntityID(ctx context.Context, entityID int64) (LegalEntity, error)
	GetNaturalPersonByLegalEntityID(ctx context.Context, legalEntityID int64) (NaturalPerson, error)
	GetOIDCConfig(ctx context.Context) (OidcConfig, error)
	// Fetch one provider override row by id.
	GetOIDCProvider(ctx context.Context, id string) (OidcProvider, error)
	GetServiceAccountByEntityID(ctx context.Context, entityID int64) (ServiceAccount, error)
	GetUserByAuth(ctx context.Context, arg GetUserByAuthParams) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	ListAppUsers(ctx context.Context, appID int64) ([]AppsUser, error)
	ListApps(ctx context.Context) ([]App, error)
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	// Return every provider override row, sorted by id for stable output.
	ListOIDCProviders(ctx context.Context) ([]OidcProvider, error)
	ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error)
	ListUserApps(ctx context.Context, userID int64) ([]AppsUser, error)
	RemoveUserFromApp(ctx context.Context, arg RemoveUserFromAppParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetAdmin(ctx context.Context, arg SetAdminParams) error
	SetAppUserRoles(ctx context.Context, arg SetAppUserRolesParams) error
	SetDefaultApp(ctx context.Context, arg SetDefaultAppParams) error
	// Narrow write used by /v1/oidc-config/confirm when the admin toggles a
	// provider on/off from the summary page. Insert creates a row with just
	// the enabled flag (all other override fields NULL → pass through to env
	// / well-known); update leaves all other columns untouched so the row's
	// existing overrides survive a simple enable/disable.
	SetOIDCProviderEnabled(ctx context.Context, arg SetOIDCProviderEnabledParams) error
	// Install or refresh the active setup-token hash; called once per boot
	// when the state is unconfirmed and no hash is already present.
	SetSetupTokenHash(ctx context.Context, setupTokenHash pgtype.Text) error
	UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
	UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) error
	UpdateNaturalPerson(ctx context.Context, arg UpdateNaturalPersonParams) error
	// Persist the operator's opt-out choice (called from POST /v1/oidc-config/confirm).
	// Per-provider enable flags live in the oidc_providers table and are
	// upserted directly — no JSONB column on this singleton since 9.16.
	UpdateOIDCConfig(ctx context.Context, optOut bool) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertAuthLocal(ctx context.Context, arg UpsertAuthLocalParams) error
	// Insert or replace a provider override row. NULL override fields mean
	// "no opinion at this layer"; the merge code treats NULL as pass-through
	// to env / well-known defaults.
	//
	// The handler is responsible for computing the merged row before
	// calling: partial PATCH semantics (e.g. "keep existing client_secret
	// when field is omitted") must be resolved in Go code, because SQL
	// NULL doesn't distinguish "field absent" from "explicit null". This
	// keeps the query trivial and the semantics readable.
	UpsertOIDCProvider(ctx context.Context, arg UpsertOIDCProviderParams) (OidcProvider, error)
	WriteAudit(ctx context.Context, arg WriteAuditParams) error
}

var _ Querier = (*Queries)(nil)
