// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (account_holder, email, email_verified_at, is_admin, auth_issuer, auth_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
          auth_issuer, auth_id, created_at, updated_at
`

type CreateUserAccountParams struct {
	AccountHolder   int64       `json:"account_holder"`
	Email           string      `json:"email"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	IsAdmin         bool        `json:"is_admin"`
	AuthIssuer      pgtype.Text `json:"auth_issuer"`
	AuthID          pgtype.Text `json:"auth_id"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.AccountHolder,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.IsAdmin,
		arg.AuthIssuer,
		arg.AuthID,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByAuth = `-- name: GetUserAccountByAuth :one
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE auth_issuer = $1 AND auth_id = $2
`

type GetUserAccountByAuthParams struct {
	AuthIssuer pgtype.Text `json:"auth_issuer"`
	AuthID     pgtype.Text `json:"auth_id"`
}

func (q *Queries) GetUserAccountByAuth(ctx context.Context, arg GetUserAccountByAuthParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByAuth, arg.AuthIssuer, arg.AuthID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByEmail = `-- name: GetUserAccountByEmail :one
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserAccountByEmail(ctx context.Context, lower string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByEmail, lower)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE id = $1
`

func (q *Queries) GetUserAccountByID(ctx context.Context, id int64) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByAccountHolder = `-- name: GetUserAccountByAccountHolder :one
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE account_holder = $1
`

func (q *Queries) GetUserAccountByAccountHolder(ctx context.Context, accountHolder int64) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByAccountHolder, accountHolder)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByUUID = `-- name: GetUserAccountByUUID :one
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE uuid = $1
`

func (q *Queries) GetUserAccountByUUID(ctx context.Context, argUuid uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByUUID, argUuid)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountHolder,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUserAccounts = `-- name: SearchUserAccounts :many
SELECT id, uuid, account_holder, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM user_accounts
WHERE ($1::text IS NULL OR lower(email) LIKE '%' || lower($1::text) || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUserAccountsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchUserAccounts(ctx context.Context, arg SearchUserAccountsParams) ([]UserAccount, error) {
	rows, err := q.db.Query(ctx, searchUserAccounts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccount
	for rows.Next() {
		var i UserAccount
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AccountHolder,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.IsAdmin,
			&i.DefaultAppID,
			&i.AuthIssuer,
			&i.AuthID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE user_accounts
SET is_admin = $2
WHERE id = $1
`

type SetAdminParams struct {
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"is_admin"`
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.Exec(ctx, setAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setDefaultApp = `-- name: SetDefaultApp :exec
UPDATE user_accounts
SET default_app_id = $2
WHERE id = $1
`

type SetDefaultAppParams struct {
	ID           int64       `json:"id"`
	DefaultAppID pgtype.Int8 `json:"default_app_id"`
}

func (q *Queries) SetDefaultApp(ctx context.Context, arg SetDefaultAppParams) error {
	_, err := q.db.Exec(ctx, setDefaultApp, arg.ID, arg.DefaultAppID)
	return err
}

const updateUserAccount = `-- name: UpdateUserAccount :exec
UPDATE user_accounts
SET email = $2,
    email_verified_at = $3,
    auth_issuer = $4,
    auth_id = $5
WHERE id = $1
`

type UpdateUserAccountParams struct {
	ID              int64       `json:"id"`
	Email           string      `json:"email"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	AuthIssuer      pgtype.Text `json:"auth_issuer"`
	AuthID          pgtype.Text `json:"auth_id"`
}

func (q *Queries) UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) error {
	_, err := q.db.Exec(ctx, updateUserAccount,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.AuthIssuer,
		arg.AuthID,
	)
	return err
}
