// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: apps_users.sql

package db

import (
	"context"
)

const assignUserToApp = `-- name: AssignUserToApp :exec
INSERT INTO apps_users (app_id, user_id, roles)
VALUES ($1, $2, $3)
ON CONFLICT (app_id, user_id) DO NOTHING
`

type AssignUserToAppParams struct {
	AppID  int64    `json:"app_id"`
	UserID int64    `json:"user_id"`
	Roles  []string `json:"roles"`
}

func (q *Queries) AssignUserToApp(ctx context.Context, arg AssignUserToAppParams) error {
	_, err := q.db.Exec(ctx, assignUserToApp, arg.AppID, arg.UserID, arg.Roles)
	return err
}

const listAppUsers = `-- name: ListAppUsers :many
SELECT app_id, user_id, roles, assigned_at
FROM apps_users
WHERE app_id = $1
ORDER BY assigned_at
`

func (q *Queries) ListAppUsers(ctx context.Context, appID int64) ([]AppsUser, error) {
	rows, err := q.db.Query(ctx, listAppUsers, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppsUser
	for rows.Next() {
		var i AppsUser
		if err := rows.Scan(
			&i.AppID,
			&i.UserID,
			&i.Roles,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApps = `-- name: ListUserApps :many
SELECT app_id, user_id, roles, assigned_at
FROM apps_users
WHERE user_id = $1
ORDER BY assigned_at
`

func (q *Queries) ListUserApps(ctx context.Context, userID int64) ([]AppsUser, error) {
	rows, err := q.db.Query(ctx, listUserApps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppsUser
	for rows.Next() {
		var i AppsUser
		if err := rows.Scan(
			&i.AppID,
			&i.UserID,
			&i.Roles,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromApp = `-- name: RemoveUserFromApp :exec
DELETE FROM apps_users
WHERE app_id = $1 AND user_id = $2
`

type RemoveUserFromAppParams struct {
	AppID  int64 `json:"app_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveUserFromApp(ctx context.Context, arg RemoveUserFromAppParams) error {
	_, err := q.db.Exec(ctx, removeUserFromApp, arg.AppID, arg.UserID)
	return err
}

const setAppUserRoles = `-- name: SetAppUserRoles :exec
UPDATE apps_users
SET roles = $3
WHERE app_id = $1 AND user_id = $2
`

type SetAppUserRolesParams struct {
	AppID  int64    `json:"app_id"`
	UserID int64    `json:"user_id"`
	Roles  []string `json:"roles"`
}

func (q *Queries) SetAppUserRoles(ctx context.Context, arg SetAppUserRolesParams) error {
	_, err := q.db.Exec(ctx, setAppUserRoles, arg.AppID, arg.UserID, arg.Roles)
	return err
}
