// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: apps.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveApp = `-- name: ArchiveApp :exec
UPDATE apps
SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveApp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveApp, id)
	return err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (slug, name)
VALUES ($1, $2)
RETURNING id, uuid, slug, name, created_at, updated_at, archived_at
`

type CreateAppParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp, arg.Slug, arg.Name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, uuid, slug, name, created_at, updated_at, archived_at
FROM apps
WHERE slug = $1
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRow(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAppByUUID = `-- name: GetAppByUUID :one
SELECT id, uuid, slug, name, created_at, updated_at, archived_at
FROM apps
WHERE uuid = $1
`

func (q *Queries) GetAppByUUID(ctx context.Context, argUuid uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getAppByUUID, argUuid)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, uuid, slug, name, created_at, updated_at, archived_at
FROM apps
WHERE archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.Query(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps
SET slug = $2, name = $3
WHERE id = $1
`

type UpdateAppParams struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.Exec(ctx, updateApp, arg.ID, arg.Slug, arg.Name)
	return err
}
