// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_local.sql

package db

import (
	"context"
)

const deleteAuthLocal = `-- name: DeleteAuthLocal :exec
DELETE FROM auth_local
WHERE user_id = $1
`

func (q *Queries) DeleteAuthLocal(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAuthLocal, userID)
	return err
}

const getAuthLocal = `-- name: GetAuthLocal :one
SELECT user_id, password_hash, password_updated_at, created_at
FROM auth_local
WHERE user_id = $1
`

func (q *Queries) GetAuthLocal(ctx context.Context, userID int64) (AuthLocal, error) {
	row := q.db.QueryRow(ctx, getAuthLocal, userID)
	var i AuthLocal
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthLocal = `-- name: UpsertAuthLocal :exec
INSERT INTO auth_local (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    password_updated_at = now()
`

type UpsertAuthLocalParams struct {
	UserID       int64  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpsertAuthLocal(ctx context.Context, arg UpsertAuthLocalParams) error {
	_, err := q.db.Exec(ctx, upsertAuthLocal, arg.UserID, arg.PasswordHash)
	return err
}
