// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: corporations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCorporation = `-- name: CreateCorporation :one
INSERT INTO corporations (legal_entity_id, legal_name, jurisdiction)
VALUES ($1, $2, $3)
RETURNING id, legal_entity_id, legal_name, jurisdiction, created_at, updated_at
`

type CreateCorporationParams struct {
	LegalEntityID int64       `json:"legal_entity_id"`
	LegalName     string      `json:"legal_name"`
	Jurisdiction  pgtype.Text `json:"jurisdiction"`
}

func (q *Queries) CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error) {
	row := q.db.QueryRow(ctx, createCorporation, arg.LegalEntityID, arg.LegalName, arg.Jurisdiction)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.LegalEntityID,
		&i.LegalName,
		&i.Jurisdiction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCorporationByLegalEntityID = `-- name: GetCorporationByLegalEntityID :one
SELECT id, legal_entity_id, legal_name, jurisdiction, created_at, updated_at
FROM corporations
WHERE legal_entity_id = $1
`

func (q *Queries) GetCorporationByLegalEntityID(ctx context.Context, legalEntityID int64) (Corporation, error) {
	row := q.db.QueryRow(ctx, getCorporationByLegalEntityID, legalEntityID)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.LegalEntityID,
		&i.LegalName,
		&i.Jurisdiction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCorporation = `-- name: UpdateCorporation :exec
UPDATE corporations
SET legal_name = $2, jurisdiction = $3
WHERE legal_entity_id = $1
`

type UpdateCorporationParams struct {
	LegalEntityID int64       `json:"legal_entity_id"`
	LegalName     string      `json:"legal_name"`
	Jurisdiction  pgtype.Text `json:"jurisdiction"`
}

func (q *Queries) UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) error {
	_, err := q.db.Exec(ctx, updateCorporation, arg.LegalEntityID, arg.LegalName, arg.Jurisdiction)
	return err
}
