// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: entities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveEntity = `-- name: ArchiveEntity :exec
UPDATE entities
SET archived_at = now()
WHERE uuid = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveEntity, argUuid)
	return err
}

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (kind)
VALUES ($1)
RETURNING id, uuid, kind, created_at, updated_at, archived_at
`

func (q *Queries) CreateEntity(ctx context.Context, kind string) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity, kind)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEntityByUUID = `-- name: GetEntityByUUID :one
SELECT id, uuid, kind, created_at, updated_at, archived_at
FROM entities
WHERE uuid = $1
`

func (q *Queries) GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByUUID, argUuid)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const unarchiveEntity = `-- name: UnarchiveEntity :exec
UPDATE entities
SET archived_at = NULL
WHERE uuid = $1 AND archived_at IS NOT NULL
`

func (q *Queries) UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveEntity, argUuid)
	return err
}
