// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: legal_entities.sql

package db

import (
	"context"
)

const createLegalEntity = `-- name: CreateLegalEntity :one
INSERT INTO legal_entities (entity_id, kind, display_name)
VALUES ($1, $2, $3)
RETURNING id, entity_id, kind, display_name, created_at, updated_at
`

type CreateLegalEntityParams struct {
	EntityID    int64  `json:"entity_id"`
	Kind        string `json:"kind"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateLegalEntity(ctx context.Context, arg CreateLegalEntityParams) (LegalEntity, error) {
	row := q.db.QueryRow(ctx, createLegalEntity, arg.EntityID, arg.Kind, arg.DisplayName)
	var i LegalEntity
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalEntityByEntityID = `-- name: GetLegalEntityByEntityID :one
SELECT id, entity_id, kind, display_name, created_at, updated_at
FROM legal_entities
WHERE entity_id = $1
`

func (q *Queries) GetLegalEntityByEntityID(ctx context.Context, entityID int64) (LegalEntity, error) {
	row := q.db.QueryRow(ctx, getLegalEntityByEntityID, entityID)
	var i LegalEntity
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
