// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

type AppsUser struct {
	AppID      int64              `json:"app_id"`
	UserID     int64              `json:"user_id"`
	Roles      []string           `json:"roles"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type AuditLog struct {
	ID             int64              `json:"id"`
	ActorUserID    int64              `json:"actor_user_id"`
	AssumedUserID  pgtype.Int8        `json:"assumed_user_id"`
	TargetEntityID pgtype.Int8        `json:"target_entity_id"`
	Op             string             `json:"op"`
	Resource       string             `json:"resource"`
	Before         []byte             `json:"before"`
	After          []byte             `json:"after"`
	At             pgtype.Timestamptz `json:"at"`
}

type AuthLocal struct {
	UserID            int64              `json:"user_id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Corporation struct {
	ID            int64              `json:"id"`
	LegalEntityID int64              `json:"legal_entity_id"`
	LegalName     string             `json:"legal_name"`
	Jurisdiction  pgtype.Text        `json:"jurisdiction"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EmailCode struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CodeHash   string             `json:"code_hash"`
	Purpose    string             `json:"purpose"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt *time.Time         `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Entity struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Kind       string             `json:"kind"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt *time.Time         `json:"archived_at"`
}

type LegalEntity struct {
	ID          int64              `json:"id"`
	EntityID    int64              `json:"entity_id"`
	Kind        string             `json:"kind"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NaturalPerson struct {
	ID            int64              `json:"id"`
	LegalEntityID int64              `json:"legal_entity_id"`
	GivenName     pgtype.Text        `json:"given_name"`
	FamilyName    pgtype.Text        `json:"family_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt *time.Time         `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ServiceAccount struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	EntityID        int64              `json:"entity_id"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	IsAdmin         bool               `json:"is_admin"`
	DefaultAppID    pgtype.Int8        `json:"default_app_id"`
	AuthIssuer      pgtype.Text        `json:"auth_issuer"`
	AuthID          pgtype.Text        `json:"auth_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
