// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveApp(ctx context.Context, id int64) error
	ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	AssignUserToApp(ctx context.Context, arg AssignUserToAppParams) error
	ConsumeEmailCode(ctx context.Context, id int64) error
	ConsumePasswordReset(ctx context.Context, id int64) error
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error)
	CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error)
	CreateEntity(ctx context.Context, kind string) (Entity, error)
	CreateLegalEntity(ctx context.Context, arg CreateLegalEntityParams) (LegalEntity, error)
	CreateNaturalPerson(ctx context.Context, arg CreateNaturalPersonParams) (NaturalPerson, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthLocal(ctx context.Context, userID int64) error
	GetActiveEmailCode(ctx context.Context, arg GetActiveEmailCodeParams) (EmailCode, error)
	GetActivePasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetAppBySlug(ctx context.Context, slug string) (App, error)
	GetAppByUUID(ctx context.Context, argUuid uuid.UUID) (App, error)
	GetAuthLocal(ctx context.Context, userID int64) (AuthLocal, error)
	GetCorporationByLegalEntityID(ctx context.Context, legalEntityID int64) (Corporation, error)
	GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (Entity, error)
	GetLegalEntityByEntityID(ctx context.Context, entityID int64) (LegalEntity, error)
	GetNaturalPersonByLegalEntityID(ctx context.Context, legalEntityID int64) (NaturalPerson, error)
	GetServiceAccountByEntityID(ctx context.Context, entityID int64) (ServiceAccount, error)
	GetUserByAuth(ctx context.Context, arg GetUserByAuthParams) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	ListAppUsers(ctx context.Context, appID int64) ([]AppsUser, error)
	ListApps(ctx context.Context) ([]App, error)
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error)
	ListUserApps(ctx context.Context, userID int64) ([]AppsUser, error)
	RemoveUserFromApp(ctx context.Context, arg RemoveUserFromAppParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetAdmin(ctx context.Context, arg SetAdminParams) error
	SetAppUserRoles(ctx context.Context, arg SetAppUserRolesParams) error
	SetDefaultApp(ctx context.Context, arg SetDefaultAppParams) error
	UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
	UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) error
	UpdateNaturalPerson(ctx context.Context, arg UpdateNaturalPersonParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertAuthLocal(ctx context.Context, arg UpsertAuthLocalParams) error
	WriteAudit(ctx context.Context, arg WriteAuditParams) error
}

var _ Querier = (*Queries)(nil)
