// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: service_accounts.sql

package db

import (
	"context"
)

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (entity_id, label)
VALUES ($1, $2)
RETURNING id, entity_id, label, created_at, updated_at
`

type CreateServiceAccountParams struct {
	EntityID int64  `json:"entity_id"`
	Label    string `json:"label"`
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount, arg.EntityID, arg.Label)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceAccountByEntityID = `-- name: GetServiceAccountByEntityID :one
SELECT id, entity_id, label, created_at, updated_at
FROM service_accounts
WHERE entity_id = $1
`

func (q *Queries) GetServiceAccountByEntityID(ctx context.Context, entityID int64) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByEntityID, entityID)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
