// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (entity_id, email, email_verified_at, is_admin, auth_issuer, auth_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
          auth_issuer, auth_id, created_at, updated_at
`

type CreateUserParams struct {
	EntityID        int64       `json:"entity_id"`
	Email           string      `json:"email"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	IsAdmin         bool        `json:"is_admin"`
	AuthIssuer      pgtype.Text `json:"auth_issuer"`
	AuthID          pgtype.Text `json:"auth_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EntityID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.IsAdmin,
		arg.AuthIssuer,
		arg.AuthID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EntityID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuth = `-- name: GetUserByAuth :one
SELECT id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM users
WHERE auth_issuer = $1 AND auth_id = $2
`

type GetUserByAuthParams struct {
	AuthIssuer pgtype.Text `json:"auth_issuer"`
	AuthID     pgtype.Text `json:"auth_id"`
}

func (q *Queries) GetUserByAuth(ctx context.Context, arg GetUserByAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth, arg.AuthIssuer, arg.AuthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EntityID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EntityID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EntityID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM users
WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EntityID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DefaultAppID,
		&i.AuthIssuer,
		&i.AuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, uuid, entity_id, email, email_verified_at, is_admin, default_app_id,
       auth_issuer, auth_id, created_at, updated_at
FROM users
WHERE ($1::text IS NULL OR lower(email) LIKE '%' || lower($1::text) || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EntityID,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.IsAdmin,
			&i.DefaultAppID,
			&i.AuthIssuer,
			&i.AuthID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users
SET is_admin = $2
WHERE id = $1
`

type SetAdminParams struct {
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"is_admin"`
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.Exec(ctx, setAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setDefaultApp = `-- name: SetDefaultApp :exec
UPDATE users
SET default_app_id = $2
WHERE id = $1
`

type SetDefaultAppParams struct {
	ID           int64       `json:"id"`
	DefaultAppID pgtype.Int8 `json:"default_app_id"`
}

func (q *Queries) SetDefaultApp(ctx context.Context, arg SetDefaultAppParams) error {
	_, err := q.db.Exec(ctx, setDefaultApp, arg.ID, arg.DefaultAppID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2,
    email_verified_at = $3,
    auth_issuer = $4,
    auth_id = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID              int64       `json:"id"`
	Email           string      `json:"email"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	AuthIssuer      pgtype.Text `json:"auth_issuer"`
	AuthID          pgtype.Text `json:"auth_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.AuthIssuer,
		arg.AuthID,
	)
	return err
}
